/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorldsRouteImport } from './routes/app/worlds'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPortalsRouteImport } from './routes/app/portals'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppExtensionsRouteImport } from './routes/app/extensions'
import { Route as AppConfigsRouteImport } from './routes/app/configs'
import { Route as AppWorldsIndexRouteImport } from './routes/app/worlds.index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile.index'
import { Route as AppWorldsCreateRouteImport } from './routes/app/worlds.create'
import { Route as AppStudioWorldIdRouteImport } from './routes/app/studio.$worldId'
import { Route as AppPreviewWorldIdRouteImport } from './routes/app/preview.$worldId'
import { Route as AppChatSessionIdRouteImport } from './routes/app/chat.$sessionId'
import { Route as AppWorldsWorldIdEditRouteImport } from './routes/app/worlds.$worldId.edit'

const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsRoute = AppWorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalsRoute = AppPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppExtensionsRoute = AppExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigsRoute = AppConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsIndexRoute = AppWorldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorldsRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppWorldsCreateRoute = AppWorldsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppWorldsRoute,
} as any)
const AppStudioWorldIdRoute = AppStudioWorldIdRouteImport.update({
  id: '/studio/$worldId',
  path: '/studio/$worldId',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewWorldIdRoute = AppPreviewWorldIdRouteImport.update({
  id: '/preview/$worldId',
  path: '/preview/$worldId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatSessionIdRoute = AppChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsWorldIdEditRoute = AppWorldsWorldIdEditRouteImport.update({
  id: '/$worldId/edit',
  path: '/$worldId/edit',
  getParentRoute: () => AppWorldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verified': typeof VerifiedRoute
  '/app/configs': typeof AppConfigsRoute
  '/app/extensions': typeof AppExtensionsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/portals': typeof AppPortalsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/worlds': typeof AppWorldsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/app/preview/$worldId': typeof AppPreviewWorldIdRoute
  '/app/studio/$worldId': typeof AppStudioWorldIdRoute
  '/app/worlds/create': typeof AppWorldsCreateRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/worlds/': typeof AppWorldsIndexRoute
  '/app/worlds/$worldId/edit': typeof AppWorldsWorldIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verified': typeof VerifiedRoute
  '/app/configs': typeof AppConfigsRoute
  '/app/extensions': typeof AppExtensionsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/portals': typeof AppPortalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/app/preview/$worldId': typeof AppPreviewWorldIdRoute
  '/app/studio/$worldId': typeof AppStudioWorldIdRoute
  '/app/worlds/create': typeof AppWorldsCreateRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/worlds': typeof AppWorldsIndexRoute
  '/app/worlds/$worldId/edit': typeof AppWorldsWorldIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verified': typeof VerifiedRoute
  '/app/configs': typeof AppConfigsRoute
  '/app/extensions': typeof AppExtensionsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/portals': typeof AppPortalsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/worlds': typeof AppWorldsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/app/preview/$worldId': typeof AppPreviewWorldIdRoute
  '/app/studio/$worldId': typeof AppStudioWorldIdRoute
  '/app/worlds/create': typeof AppWorldsCreateRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/worlds/': typeof AppWorldsIndexRoute
  '/app/worlds/$worldId/edit': typeof AppWorldsWorldIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/delete-account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified'
    | '/app/configs'
    | '/app/extensions'
    | '/app/library'
    | '/app/portals'
    | '/app/profile'
    | '/app/settings'
    | '/app/worlds'
    | '/app/'
    | '/app/chat/$sessionId'
    | '/app/preview/$worldId'
    | '/app/studio/$worldId'
    | '/app/worlds/create'
    | '/app/profile/'
    | '/app/worlds/'
    | '/app/worlds/$worldId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delete-account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified'
    | '/app/configs'
    | '/app/extensions'
    | '/app/library'
    | '/app/portals'
    | '/app/settings'
    | '/app'
    | '/app/chat/$sessionId'
    | '/app/preview/$worldId'
    | '/app/studio/$worldId'
    | '/app/worlds/create'
    | '/app/profile'
    | '/app/worlds'
    | '/app/worlds/$worldId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/delete-account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified'
    | '/app/configs'
    | '/app/extensions'
    | '/app/library'
    | '/app/portals'
    | '/app/profile'
    | '/app/settings'
    | '/app/worlds'
    | '/app/'
    | '/app/chat/$sessionId'
    | '/app/preview/$worldId'
    | '/app/studio/$worldId'
    | '/app/worlds/create'
    | '/app/profile/'
    | '/app/worlds/'
    | '/app/worlds/$worldId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifiedRoute: typeof VerifiedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worlds': {
      id: '/app/worlds'
      path: '/worlds'
      fullPath: '/app/worlds'
      preLoaderRoute: typeof AppWorldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portals': {
      id: '/app/portals'
      path: '/portals'
      fullPath: '/app/portals'
      preLoaderRoute: typeof AppPortalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/extensions': {
      id: '/app/extensions'
      path: '/extensions'
      fullPath: '/app/extensions'
      preLoaderRoute: typeof AppExtensionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configs': {
      id: '/app/configs'
      path: '/configs'
      fullPath: '/app/configs'
      preLoaderRoute: typeof AppConfigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worlds/': {
      id: '/app/worlds/'
      path: '/'
      fullPath: '/app/worlds/'
      preLoaderRoute: typeof AppWorldsIndexRouteImport
      parentRoute: typeof AppWorldsRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/worlds/create': {
      id: '/app/worlds/create'
      path: '/create'
      fullPath: '/app/worlds/create'
      preLoaderRoute: typeof AppWorldsCreateRouteImport
      parentRoute: typeof AppWorldsRoute
    }
    '/app/studio/$worldId': {
      id: '/app/studio/$worldId'
      path: '/studio/$worldId'
      fullPath: '/app/studio/$worldId'
      preLoaderRoute: typeof AppStudioWorldIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preview/$worldId': {
      id: '/app/preview/$worldId'
      path: '/preview/$worldId'
      fullPath: '/app/preview/$worldId'
      preLoaderRoute: typeof AppPreviewWorldIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$sessionId': {
      id: '/app/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/app/chat/$sessionId'
      preLoaderRoute: typeof AppChatSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worlds/$worldId/edit': {
      id: '/app/worlds/$worldId/edit'
      path: '/$worldId/edit'
      fullPath: '/app/worlds/$worldId/edit'
      preLoaderRoute: typeof AppWorldsWorldIdEditRouteImport
      parentRoute: typeof AppWorldsRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppWorldsRouteChildren {
  AppWorldsCreateRoute: typeof AppWorldsCreateRoute
  AppWorldsIndexRoute: typeof AppWorldsIndexRoute
  AppWorldsWorldIdEditRoute: typeof AppWorldsWorldIdEditRoute
}

const AppWorldsRouteChildren: AppWorldsRouteChildren = {
  AppWorldsCreateRoute: AppWorldsCreateRoute,
  AppWorldsIndexRoute: AppWorldsIndexRoute,
  AppWorldsWorldIdEditRoute: AppWorldsWorldIdEditRoute,
}

const AppWorldsRouteWithChildren = AppWorldsRoute._addFileChildren(
  AppWorldsRouteChildren,
)

interface AppRouteChildren {
  AppConfigsRoute: typeof AppConfigsRoute
  AppExtensionsRoute: typeof AppExtensionsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPortalsRoute: typeof AppPortalsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorldsRoute: typeof AppWorldsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatSessionIdRoute: typeof AppChatSessionIdRoute
  AppPreviewWorldIdRoute: typeof AppPreviewWorldIdRoute
  AppStudioWorldIdRoute: typeof AppStudioWorldIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfigsRoute: AppConfigsRoute,
  AppExtensionsRoute: AppExtensionsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPortalsRoute: AppPortalsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppWorldsRoute: AppWorldsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatSessionIdRoute: AppChatSessionIdRoute,
  AppPreviewWorldIdRoute: AppPreviewWorldIdRoute,
  AppStudioWorldIdRoute: AppStudioWorldIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifiedRoute: VerifiedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
