#!/usr/bin/env node
/**
 * `pnpm start` for the open-source edition.
 *
 * What it does, in order:
 *   1. Makes sure a root `.env` exists with a stable BETTER_AUTH_SECRET. That
 *      secret signs your session cookie AND encrypts the API keys you store, so
 *      it is generated once and kept. Never commit `.env`.
 *   2. Builds the app on first run (or with --build), then copies the built
 *      frontend into the server's public folder, exactly like the Docker image.
 *   3. Starts the server in production mode. Open the printed URL.
 *
 * Everything else is ordinary environment: PORT, HOST, YUMINA_DATA_DIR, ...
 * See .env.example for the full list.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SERVER_DIR = path.join(ROOT, "packages", "server");
const APP_DIST = path.join(ROOT, "packages", "app", "dist");
const SERVER_PUBLIC = path.join(SERVER_DIR, "public");
const SERVER_ENTRY = path.join(SERVER_DIR, "dist", "index.js");
const ENV_FILE = path.join(ROOT, ".env");
const wantBuild = process.argv.includes("--build");
const isWin = process.platform === "win32";

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) return {};
  const out = {};
  for (const line of fs.readFileSync(ENV_FILE, "utf8").split(/\r?\n/)) {
    const m = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

function ensureEnv() {
  const fileEnv = readEnvFile();
  const additions = [];
  if (!process.env.BETTER_AUTH_SECRET && !fileEnv.BETTER_AUTH_SECRET) {
    additions.push(`BETTER_AUTH_SECRET=${crypto.randomBytes(32).toString("hex")}`);
  }
  if (!process.env.YUMINA_EDITION && !fileEnv.YUMINA_EDITION) {
    additions.push("YUMINA_EDITION=local");
  }
  if (additions.length) {
    const header = fs.existsSync(ENV_FILE) ? "\n" : "# Generated by `pnpm start`. Keep this file private; it is gitignored.\n";
    fs.appendFileSync(ENV_FILE, header + additions.join("\n") + "\n");
    console.log(`[start] wrote ${additions.map((a) => a.split("=")[0]).join(", ")} to .env`);
  }
  return { ...readEnvFile(), ...process.env };
}

function run(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, { stdio: "inherit", cwd: ROOT, shell: isWin, ...opts });
  if (res.status !== 0) {
    console.error(`[start] ${cmd} ${args.join(" ")} failed (exit ${res.status ?? "signal"})`);
    process.exit(res.status ?? 1);
  }
}

function needsBuild() {
  return wantBuild || !fs.existsSync(SERVER_ENTRY) || !fs.existsSync(path.join(APP_DIST, "index.html"));
}

function syncPublic() {
  fs.rmSync(SERVER_PUBLIC, { recursive: true, force: true });
  fs.cpSync(APP_DIST, SERVER_PUBLIC, { recursive: true });
}

const env = ensureEnv();
env.VITE_EDITION = "local";
env.YUMINA_EDITION = env.YUMINA_EDITION || "local";

if (needsBuild()) {
  console.log("[start] building (first run takes a few minutes)...");
  run("pnpm", ["build"], { env });
}
syncPublic();

const host = env.HOST || "127.0.0.1";
const port = env.PORT || "3000";
console.log(`[start] Yumina is starting at http://${host === "0.0.0.0" ? "localhost" : host}:${port}`);

const child = spawn("node", ["dist/index.js"], {
  cwd: SERVER_DIR,
  stdio: "inherit",
  env: { ...env, NODE_ENV: "production" },
});
child.on("exit", (code) => process.exit(code ?? 0));
for (const sig of ["SIGINT", "SIGTERM"]) {
  process.on(sig, () => child.kill(sig));
}
