/**
 * The generated `index.tsx` a card gets once it has installed a bundle with UI.
 *
 * Contract (shared by the app's editor store and the server's Studio tools, so
 * both sides produce byte-identical files — a save on either side must never
 * look like an edit to the other):
 *   - entryFile is ALWAYS "index.tsx".
 *   - The author's own main UI lives in `__user-root.tsx`.
 *   - Each installed bundle lives under `_bundles/{slug}/`, entry `index.tsx`.
 *   - The composer imports every bundle as a namespace. A bundle that exports
 *     `app` metadata is an App: it goes into one shared dock instead of drawing
 *     its own floating button. Any other bundle mounts as a sibling overlay,
 *     exactly as before, so older bundles keep working untouched.
 *
 * `app` metadata: { id, icon, name, variable, accent, accent2?, lang?, badge?(data) }.
 * `badge` returns a count to show on the dock tile (unread texts…); without
 * it the tile gets a dot whenever the App's variable changed unseen.
 */

export const USER_ROOT_PATH = "__user-root.tsx";
export const COMPOSED_MARKER = "// AUTO-GENERATED by importBundle";
/** Matches the entry file of a bundle namespace folder. */
export const BUNDLE_NS_RE = /^_bundles\/([^/]+)\/index\.tsx$/;

/** The dock that hosts every App bundle. Kept free of backticks and template
 *  placeholders so it can live inside the generated string verbatim. */
const APP_DOCK_TSX = `
const DOCK_HINT = {
  zh: "剧情里的 App 都在这里：消息、关系、时间……随剧情自动更新。",
  en: "Your in-story apps live here — messages, relationships, time… they update as the story moves.",
  es: "Aquí están las apps de la historia: mensajes, relaciones, tiempo… se actualizan solas.",
};

function readAppState(api, app) {
  if (!app || !app.variable) return "";
  try { return JSON.stringify(api.variables[app.variable] ?? null); } catch (e) { return ""; }
}

function readBadge(api, app) {
  if (!app || typeof app.badge !== "function") return 0;
  try { return Number(app.badge(api.variables[app.variable] || {})) || 0; } catch (e) { return 0; }
}

function AppDock({ apps }) {
  const api = useYumina();
  const [openId, setOpenId] = React.useState(null);
  const [folded, setFolded] = React.useState(false);
  const [narrow, setNarrow] = React.useState(typeof window !== "undefined" && window.innerWidth < 720);
  const [hint, setHint] = React.useState(() => {
    try { return !window.localStorage.getItem("yumina_app_dock_hint_seen"); } catch (e) { return false; }
  });
  const seen = React.useRef({});
  const list = apps.map((b) => b.app).filter(Boolean);
  const lang = (list[0] && list[0].lang) || "en";

  React.useEffect(() => {
    const onResize = () => setNarrow(window.innerWidth < 720);
    const onKey = (e) => { if (e.key === "Escape") setOpenId(null); };
    window.addEventListener("resize", onResize);
    window.addEventListener("keydown", onKey);
    return () => { window.removeEventListener("resize", onResize); window.removeEventListener("keydown", onKey); };
  }, []);

  const dismissHint = () => {
    setHint(false);
    try { window.localStorage.setItem("yumina_app_dock_hint_seen", "1"); } catch (e) {}
  };

  // First sight of each App counts as seen, so nothing is flagged on load.
  for (const app of list) {
    if (seen.current[app.id] === undefined) seen.current[app.id] = readAppState(api, app);
  }
  if (openId) {
    const open = list.find((a) => a.id === openId);
    if (open) seen.current[open.id] = readAppState(api, open);
  }

  const openBundle = apps.find((b) => b.app && b.app.id === openId);
  const OpenApp = openBundle ? openBundle.default : null;
  const openMeta = openBundle ? openBundle.app : null;

  const toggle = (id) => { dismissHint(); setOpenId(openId === id ? null : id); };

  const dockStyle = {
    position: "fixed", right: 10, top: "50%", transform: "translateY(-50%)", zIndex: 60,
    display: "flex", flexDirection: "column", alignItems: "center", gap: 7, padding: "8px 7px",
    borderRadius: 24, background: "rgba(20,22,32,0.66)", border: "1px solid rgba(255,255,255,0.12)",
    boxShadow: "0 10px 30px rgba(0,0,0,0.30)", backdropFilter: "blur(14px)", WebkitBackdropFilter: "blur(14px)",
    visibility: narrow && openId ? "hidden" : "visible",
    maxHeight: "calc(100% - 24px)", overflowY: "auto", scrollbarWidth: "none",
  };
  const tile = (app, active) => ({
    position: "relative", width: 42, height: 42, borderRadius: 13, border: "none", cursor: "pointer",
    display: "grid", placeItems: "center", fontSize: 21, lineHeight: 1, padding: 0,
    background: "linear-gradient(145deg, " + (app.accent || "#8b93ff") + ", " + (app.accent2 || app.accent || "#5b63d6") + ")",
    boxShadow: active ? "0 0 0 2px #fff, 0 6px 16px rgba(0,0,0,0.35)" : "0 3px 10px rgba(0,0,0,0.25), inset 0 1px 0 rgba(255,255,255,0.35)",
    transform: active ? "scale(1.06)" : "none", transition: "transform .15s, box-shadow .15s",
  });
  const panelStyle = narrow
    ? { position: "fixed", left: 0, right: 0, bottom: 0, height: "82%", zIndex: 61, borderRadius: "22px 22px 0 0" }
    : { position: "fixed", right: 72, top: 14, bottom: 14, width: "min(410px, calc(100vw - 96px))", zIndex: 61, borderRadius: 22 };

  return (
    <>
      <div style={dockStyle} role="toolbar" aria-label="Apps">
        <button type="button" onClick={() => setFolded(!folded)} aria-label={folded ? "Show apps" : "Hide apps"}
          style={{ width: 24, height: 12, border: "none", background: "transparent", cursor: "pointer", padding: 0, display: "grid", placeItems: "center" }}>
          <span style={{ width: 18, height: 4, borderRadius: 2, background: "rgba(255,255,255,0.5)" }} />
        </button>
        {!folded && list.map((app) => {
          const count = readBadge(api, app);
          const changed = openId !== app.id && seen.current[app.id] !== readAppState(api, app);
          return (
            <button key={app.id} type="button" title={app.name} aria-label={app.name}
              onClick={() => toggle(app.id)} style={tile(app, openId === app.id)}>
              <span aria-hidden="true" style={{ filter: "drop-shadow(0 1px 1px rgba(0,0,0,0.25))" }}>{app.icon}</span>
              {count > 0 ? (
                <span style={{ position: "absolute", top: -5, right: -5, minWidth: 18, height: 18, padding: "0 5px", borderRadius: 9, background: "#ff3b4e", color: "#fff", fontSize: 11, fontWeight: 800, display: "grid", placeItems: "center", boxShadow: "0 0 0 2px rgba(20,22,32,0.9)", fontFamily: "system-ui, sans-serif" }}>{count > 99 ? "99+" : count}</span>
              ) : changed ? (
                <span style={{ position: "absolute", top: -3, right: -3, width: 11, height: 11, borderRadius: 6, background: "#3d8bff", boxShadow: "0 0 0 2px rgba(20,22,32,0.9)" }} />
              ) : null}
            </button>
          );
        })}
      </div>
      {hint && !openId && !folded && list.length > 0 ? (
        <button type="button" onClick={dismissHint}
          style={{ position: "fixed", right: 76, top: "50%", transform: "translateY(-50%)", zIndex: 60, maxWidth: 230, textAlign: "left",
            border: "none", cursor: "pointer", padding: "11px 14px", borderRadius: 14, background: "#fff", color: "#1b1e2b",
            fontSize: 13, lineHeight: 1.55, boxShadow: "0 10px 30px rgba(0,0,0,0.30)", fontFamily: "system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif" }}>
          {DOCK_HINT[lang] || DOCK_HINT.en}
          <span style={{ position: "absolute", right: -6, top: "50%", marginTop: -6, width: 12, height: 12, background: "#fff", transform: "rotate(45deg)" }} />
        </button>
      ) : null}
      {OpenApp && openMeta ? (
        <div style={{ ...panelStyle, display: "flex", flexDirection: "column", overflow: "hidden",
          background: "#f4f5f9", color: "#1b1e2b", boxShadow: "0 24px 60px rgba(0,0,0,0.40)",
          fontFamily: "system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', 'Segoe UI', sans-serif" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, padding: "12px 14px", background: "#fff", borderBottom: "1px solid #eceef4" }}>
            <span aria-hidden="true" style={{ width: 30, height: 30, borderRadius: 9, display: "grid", placeItems: "center", fontSize: 17,
              background: "linear-gradient(145deg, " + (openMeta.accent || "#8b93ff") + ", " + (openMeta.accent2 || openMeta.accent || "#5b63d6") + ")" }}>{openMeta.icon}</span>
            <b style={{ fontSize: 16, flex: 1, letterSpacing: ".01em" }}>{openMeta.name}</b>
            <button type="button" onClick={() => setOpenId(null)} aria-label="Close"
              style={{ width: 30, height: 30, borderRadius: 15, border: "none", cursor: "pointer", background: "#eef0f5", color: "#5b6075", fontSize: 17, lineHeight: 1 }}>×</button>
          </div>
          <div style={{ flex: 1, minHeight: 0, overflowY: "auto", display: "flex", flexDirection: "column" }}>
            <OpenApp close={() => setOpenId(null)} />
          </div>
        </div>
      ) : null}
    </>
  );
}
`;

export function generateComposedIndex(bundleFolders: string[]): string {
  const imports = [
    `import UserRoot from "./__user-root";`,
    ...bundleFolders.map((f, i) => `import * as Bundle${i} from "./_bundles/${f}/index";`),
  ];
  const list = bundleFolders.map((_, i) => `Bundle${i}`).join(", ");
  return (
    `${COMPOSED_MARKER} — do not edit. Regenerated on every bundle import.\n` +
    `// Edit ./__user-root.tsx to change your main UI.\n` +
    imports.join("\n") +
    `\n\nconst BUNDLES = [${list}];\n` +
    APP_DOCK_TSX +
    `\nexport default function App() {\n` +
    `  // An App installed twice keeps one dock button: the first copy wins.\n` +
    `  const apps = BUNDLES.filter((b, i) => b && b.app && b.default && BUNDLES.findIndex((o) => o && o.app && o.app.id === b.app.id) === i);\n` +
    `  const overlays = BUNDLES.filter((b) => b && !b.app && b.default);\n` +
    `  return (\n` +
    `    <>\n` +
    `      <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", minHeight: 0 }}>\n` +
    `        <UserRoot />\n` +
    `      </div>\n` +
    `      {overlays.map((b, i) => { const Overlay = b.default; return <Overlay key={i} />; })}\n` +
    `      {apps.length > 0 ? <AppDock apps={apps} /> : null}\n` +
    `    </>\n` +
    `  );\n` +
    `}\n`
  );
}
